spring.application.name=tlu_opiteed
server.port=8090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8nr3d3eo5us738b9a7g-a.ohio-postgres.render.com/opiteede_visualiseerimine_database
spring.datasource.username=opiteede_visualiseerimine_database_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
