spring.application.name=tlu_opiteed

# Multipart upload size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.port=8090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/opiteed_db
spring.datasource.username=postgres
spring.datasource.password=tere123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=opiteed-tlu-super-secret-jwt-signing-key-minimum-256-bits-long
jwt.expiration=86400000